export function renderDashboardHtml() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Polymarket Intelligence</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui;background:#090b10;color:#f5f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1400px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center}.brand{font-size:22px;font-weight:750}.muted{color:#9299a8}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px;margin-top:18px}.card{background:#11151d;border:1px solid #242a35;border-radius:18px;padding:18px}.span8{grid-column:span 8}.span4{grid-column:span 4}.span6{grid-column:span 6}h2{font-size:16px;margin:0 0 14px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between;padding:10px 0;border-top:1px solid #202632}.row:first-of-type{border-top:0}.pill{font-size:12px;padding:5px 8px;border-radius:999px;background:#202735}.green{color:#77f2ad}.red{color:#ff8b98}button,input,select,textarea{background:#0d1118;color:#f5f7fb;border:1px solid #303744;border-radius:10px;padding:10px}button{cursor:pointer;font-weight:650}.stack{display:flex;gap:8px;flex-wrap:wrap}.metric{font-size:28px;font-weight:750}.chat{min-height:220px;white-space:pre-wrap;overflow:auto}.small{font-size:12px}.opp{padding:12px;border:1px solid #252b36;border-radius:14px;margin:9px 0}.opp b{display:block;margin-bottom:4px}@media(max-width:900px){.span8,.span4,.span6{grid-column:span 12}.wrap{padding:16px}}
</style></head><body><main class="wrap">
<div class="top"><div><div class="brand">Polymarket Intelligence</div><div class="muted small">Live scanner · historical replay · GPT research · non-custodial wallet</div></div><div class="stack"><span id="health" class="pill">Loading</span><button id="wallet">Connect Wallet</button></div></div>
<section class="grid">
<div class="card span8"><h2>Live Opportunities</h2><div class="stack"><select id="lane"><option value="urgent_2h">≤2h urgent</option><option value="developing_6h">≤6h</option><option value="broader_24h">≤24h</option><option value="structural">Structural</option></select><button id="refresh">Refresh</button></div><div id="opps"></div></div>
<div class="card span4"><h2>System</h2><div class="row"><span class="muted">Scanner</span><span id="scanner">—</span></div><div class="row"><span class="muted">Streams</span><span id="streams">—</span></div><div class="row"><span class="muted">History</span><span id="history">—</span></div><div class="row"><span class="muted">Maintenance</span><span id="maintenance">—</span></div></div><div class="card span6"><h2>Production Readiness</h2><div class="row"><span class="muted">Causal-v2 rebuild</span><span id="causalProgress">—</span></div><div class="row"><span class="muted">Usable causal coverage</span><span id="causalCoverage">—</span></div><div class="row"><span class="muted">Directional gate</span><span id="directionalGate">—</span></div><div class="row"><span class="muted">Enabled horizons</span><span id="enabledHorizons">—</span></div><div class="row"><span class="muted">$100 holdout bankroll</span><span id="bankroll100">—</span></div><div class="row"><span class="muted">Urgent tested fill capacity</span><span id="liveCapacity">—</span></div><div class="row"><span class="muted">Turnover upper bound</span><span id="dailyCapacity">—</span></div><div class="row"><span class="muted">Paper engine</span><span id="paperState">—</span></div><div class="row"><span class="muted">Paper resolved / open</span><span id="paperTrades">—</span></div><div class="row"><span class="muted">Paper avg filled turnover/day</span><span id="paperTurnover">—</span></div><div class="row"><span class="muted">Structural rejection leader</span><span id="structuralRejects">—</span></div><div class="muted small">Capacity is a fill/turnover bound, not a profit forecast. Directional execution stays blocked until causal history and the domain-specific calendar gate pass.</div></div>
<div class="card span6"><h2>Historical Replay</h2><div class="stack"><select id="horizon"><option>tMinus120m</option><option selected>tMinus60m</option><option>tMinus30m</option><option>tMinus15m</option><option>tMinus5m</option></select><input id="threshold" type="number" min=".5" max=".99" step=".01" value=".75"><button id="runReplay">Run replay</button></div><div class="row"><span class="muted">Threshold holdout hit rate</span><span class="metric" id="hit">—</span></div><div class="row"><span class="muted">Threshold holdout ROI</span><span id="roi">—</span></div><div class="row"><span class="muted">Calibrated validation ROI</span><span id="calValRoi">—</span></div><div class="row"><span class="muted">Calibrated holdout ROI</span><span id="calHoldRoi">—</span></div><div class="row"><span class="muted">Calibrated holdout trades</span><span id="calTrades">—</span></div><div class="row"><span class="muted">Deployment gate</span><span id="deployGate">—</span></div><div class="row"><span class="muted">Walk-forward gate</span><span id="walkGate">—</span></div><div class="row"><span class="muted">Worst fold ROI</span><span id="walkMinRoi">—</span></div><div class="row"><span class="muted">Final holdout ROI</span><span id="walkHoldRoi">—</span></div><div class="row"><span class="muted">Max drawdown / $1 stake</span><span id="dd">—</span></div><div class="row"><span class="muted">Threshold trades</span><span id="trades">—</span></div><div class="row"><span class="muted">Profitable active days</span><span id="profitDays">—</span></div><div class="row"><span class="muted">Avg daily P&L / $1 stake</span><span id="avgDailyPnl">—</span></div><div class="row"><span class="muted">$100/day turnover needed</span><span id="turn100">—</span></div><div class="row"><span class="muted">$500/day turnover needed</span><span id="turn500">—</span></div><div class="row"><span class="muted">$1k/day turnover needed</span><span id="turn1000">—</span></div><div class="muted small">A calibrated policy must clear validation ROI, a 95% validation hit-rate floor, and a larger untouched holdout sample before it is marked deployable.</div></div>
<div class="card span6"><h2>Ask GPT</h2><div class="stack"><input id="controlToken" type="password" autocomplete="off" placeholder="Control token"></div><textarea id="prompt" rows="4" style="width:100%" placeholder="Analyze the strongest current opportunities and explain the execution risks."></textarea><div class="stack" style="margin-top:8px"><button id="ask">Ask GPT</button></div><div id="chat" class="chat muted small">GPT analysis appears here when a server-side API key is configured.</div></div>
</section></main>
<script>
const $=id=>document.getElementById(id);
async function j(url,opts){const r=await fetch(url,opts);const x=await r.json();if(!r.ok)throw new Error(x.message||x.error||r.status);return x}
function authed(opts={}){const token=$('controlToken')?.value?.trim();const headers={...(opts.headers||{})};if(token)headers.authorization='Bearer '+token;return {...opts,headers}}
function pct(v){return v==null?'—':Number(v).toFixed(2)+'%'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function health(){try{const x=await j('/health/deep');$('health').textContent=x.ok?'Healthy':'Degraded';$('health').className='pill '+(x.ok?'green':'red');for(const k of ['scanner','streams','history','maintenance'])$(k).textContent=x.workers?.[k]?.status||'unknown'}catch(e){$('health').textContent='Offline';$('health').className='pill red'}}async function validation(){try{const [cal,cap,paper,policy]=await Promise.all([j('/api/calibration-health'),j('/api/liquidity-capacity?lane=urgent_2h&limit=100'),j('/api/paper-trading?limit=5'),j('/api/strategy-policy')]);$('causalProgress').textContent=pct(cal.causalRebuildProgressPct);$('causalCoverage').textContent=pct(cal.causalV2UsableCoveragePct)+' / '+pct(cal.minUsableCoveragePct);$('directionalGate').textContent=policy.directionalProbabilityModelEnabled?'PASS':'HOLD';$('directionalGate').className=policy.directionalProbabilityModelEnabled?'green':'red';const pairs=[];let firstSim=null;for(const [domain,row] of Object.entries(policy.perDomain||{})){for(const h of (row.enabledHorizons||[])){pairs.push(domain+':'+h);if(!firstSim)firstSim=row.horizons?.[h]?.calendarWalkForward?.bankrollSimulation||null;}}$('enabledHorizons').textContent=pairs.length?pairs.join(', '):'None';$('bankroll100').textContent=firstSim?.endBankrollUsd==null?'—':'cap.totals?.totalMaxTestedFullFillUsd==null?'—':'$'+Number(cap.totals.totalMaxTestedFullFillUsd).toLocaleString();$('dailyCapacity').textContent=cap.totals?.stationaryDailyTurnoverUpperBoundUsd==null?'—':'$'+Number(cap.totals.stationaryDailyTurnoverUpperBoundUsd).toLocaleString();const ps=paper.stats||{};$('paperState').textContent=paper.enabled?(paper.requireCausalV2Complete&&!cal.productionGateReady?'WAITING FOR CAUSAL V2':'ENABLED'):'OFF';$('paperState').className=paper.enabled?'green':'red';$('paperTrades').textContent=(ps.resolvedTrades??0)+' / '+(ps.openTrades??0);$('paperTurnover').textContent=ps.liveDailyCapacity?.avgFilledTurnoverUsdPerActiveDay==null?'—':'$'+Number(ps.liveDailyCapacity.avgFilledTurnoverUsdPerActiveDay).toLocaleString()}catch(e){$('causalProgress').textContent='Error';$('directionalGate').textContent='HOLD';$('directionalGate').className='red'}}
async function opportunities(){const lane=$('lane').value;$('opps').innerHTML='<div class="muted">Loading…</div>';try{const x=await j('/api/unified-opportunities?lane='+encodeURIComponent(lane)+'&limit=40');$('opps').innerHTML=(x.opportunities||[]).map(o=>'<div class="opp"><b>'+esc(o.market.question)+'</b><div class="small muted">'+Number(o.market.minutesRemaining).toFixed(1)+'m · $'+Number(o.market.liquidityUsd).toLocaleString()+' liquidity · '+esc((o.strategies||[]).map(s=>s.label).join(' · '))+'</div><div class="small">Discovery '+Number(o.scores.discovery).toFixed(1)+' · Net ROI '+pct(o.economics.netRoiPct)+'</div></div>').join('')||'<div class="muted">No opportunities in this lane.</div>'}catch(e){$('opps').innerHTML='<div class="red">'+esc(e.message)+'</div>'}}
async function replay(){try{const q=new URLSearchParams({horizon:$('horizon').value,threshold:$('threshold').value,years:'3'});const x=await j('/api/historical-replay?'+q);const h=x.backtest.holdout;const c=x.calibrated||{};const w=x.walkForward||{};const d=x.backtest.holdoutDaily||{};$('hit').textContent=pct(h.hitRatePct);$('roi').textContent=pct(h.roiPct);$('dd').textContent=Number(h.maxDrawdownPerDollarStake).toFixed(3);$('trades').textContent=h.trades;$('profitDays').textContent=d.activeDays?((d.profitableDays??0)+'/'+d.activeDays+' ('+pct(d.profitableDayPct)+')'):'—';$('avgDailyPnl').textContent=d.avgPnlPerDollarStakePerDay==null?'—':'$'+Number(d.avgPnlPerDollarStakePerDay).toFixed(3);$('turn100').textContent=d.requiredDailyTurnoverUsd?.target100==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target100).toLocaleString();$('turn500').textContent=d.requiredDailyTurnoverUsd?.target500==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target500).toLocaleString();$('turn1000').textContent=d.requiredDailyTurnoverUsd?.target1000==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target1000).toLocaleString();$('calValRoi').textContent=pct(c.validation?.roiPct);$('calHoldRoi').textContent=pct(c.holdout?.roiPct);$('calTrades').textContent=c.holdout?.trades??'—';$('deployGate').textContent=c.deployable?'PASS':'HOLD';$('deployGate').className=c.deployable?'green':'red';$('walkGate').textContent=w.deployable?'PASS':'HOLD';$('walkGate').className=w.deployable?'green':'red';$('walkMinRoi').textContent=pct(w.foldSummary?.minRoiPct);$('walkHoldRoi').textContent=pct(w.holdout?.roiPct)}catch(e){$('hit').textContent='Error';$('roi').textContent=e.message;$('deployGate').textContent='Error';$('deployGate').className='red'}}
$('wallet').onclick=async()=>{try{if(!window.ethereum)throw new Error('No EVM wallet found in this browser');const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)throw new Error('Wallet did not return an address');const x=await j('/api/wallet/connect',authed({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address})}));$('wallet').textContent=x.walletAddress?.slice(0,6)+'…'+x.walletAddress?.slice(-4)}catch(e){alert(e.message)}}
$('ask').onclick=async()=>{const prompt=$('prompt').value.trim();if(!prompt)return;$('chat').textContent='Thinking…';try{const x=await j('/api/gpt',authed({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt})}));$('chat').textContent=x.text||JSON.stringify(x,null,2)}catch(e){$('chat').textContent=e.message}}
$('runReplay').onclick=replay;$('refresh').onclick=opportunities;$('lane').onchange=opportunities;health();validation();opportunities();replay();setInterval(health,15000);setInterval(validation,30000);setInterval(opportunities,30000);
</script></body></html>`;
}
+Number(firstSim.endBankrollUsd).toFixed(2)+' ('+pct(firstSim.growthPct)+')';const sd=cap.structuralDiagnostics||{};const rejectionEntries=Object.entries(sd).filter(([k,v])=>k.startsWith('rejected')&&Number(v)>0).sort((a,b)=>Number(b[1])-Number(a[1]));$('structuralRejects').textContent=rejectionEntries.length?(rejectionEntries[0][0].replace('rejected','')+': '+rejectionEntries[0][1]):'—';$('liveCapacity').textContent=cap.totals?.totalMaxTestedFullFillUsd==null?'—':'$'+Number(cap.totals.totalMaxTestedFullFillUsd).toLocaleString();$('dailyCapacity').textContent=cap.totals?.stationaryDailyTurnoverUpperBoundUsd==null?'—':'$'+Number(cap.totals.stationaryDailyTurnoverUpperBoundUsd).toLocaleString();const ps=paper.stats||{};$('paperState').textContent=paper.enabled?(paper.requireCausalV2Complete&&!cal.productionGateReady?'WAITING FOR CAUSAL V2':'ENABLED'):'OFF';$('paperState').className=paper.enabled?'green':'red';$('paperTrades').textContent=(ps.resolvedTrades??0)+' / '+(ps.openTrades??0);$('paperTurnover').textContent=ps.liveDailyCapacity?.avgFilledTurnoverUsdPerActiveDay==null?'—':'$'+Number(ps.liveDailyCapacity.avgFilledTurnoverUsdPerActiveDay).toLocaleString()}catch(e){$('causalProgress').textContent='Error';$('directionalGate').textContent='HOLD';$('directionalGate').className='red'}}
async function opportunities(){const lane=$('lane').value;$('opps').innerHTML='<div class="muted">Loading…</div>';try{const x=await j('/api/unified-opportunities?lane='+encodeURIComponent(lane)+'&limit=40');$('opps').innerHTML=(x.opportunities||[]).map(o=>'<div class="opp"><b>'+esc(o.market.question)+'</b><div class="small muted">'+Number(o.market.minutesRemaining).toFixed(1)+'m · $'+Number(o.market.liquidityUsd).toLocaleString()+' liquidity · '+esc((o.strategies||[]).map(s=>s.label).join(' · '))+'</div><div class="small">Discovery '+Number(o.scores.discovery).toFixed(1)+' · Net ROI '+pct(o.economics.netRoiPct)+'</div></div>').join('')||'<div class="muted">No opportunities in this lane.</div>'}catch(e){$('opps').innerHTML='<div class="red">'+esc(e.message)+'</div>'}}
async function replay(){try{const q=new URLSearchParams({horizon:$('horizon').value,threshold:$('threshold').value,years:'3'});const x=await j('/api/historical-replay?'+q);const h=x.backtest.holdout;const c=x.calibrated||{};const w=x.walkForward||{};const d=x.backtest.holdoutDaily||{};$('hit').textContent=pct(h.hitRatePct);$('roi').textContent=pct(h.roiPct);$('dd').textContent=Number(h.maxDrawdownPerDollarStake).toFixed(3);$('trades').textContent=h.trades;$('profitDays').textContent=d.activeDays?((d.profitableDays??0)+'/'+d.activeDays+' ('+pct(d.profitableDayPct)+')'):'—';$('avgDailyPnl').textContent=d.avgPnlPerDollarStakePerDay==null?'—':'$'+Number(d.avgPnlPerDollarStakePerDay).toFixed(3);$('turn100').textContent=d.requiredDailyTurnoverUsd?.target100==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target100).toLocaleString();$('turn500').textContent=d.requiredDailyTurnoverUsd?.target500==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target500).toLocaleString();$('turn1000').textContent=d.requiredDailyTurnoverUsd?.target1000==null?'—':'$'+Number(d.requiredDailyTurnoverUsd.target1000).toLocaleString();$('calValRoi').textContent=pct(c.validation?.roiPct);$('calHoldRoi').textContent=pct(c.holdout?.roiPct);$('calTrades').textContent=c.holdout?.trades??'—';$('deployGate').textContent=c.deployable?'PASS':'HOLD';$('deployGate').className=c.deployable?'green':'red';$('walkGate').textContent=w.deployable?'PASS':'HOLD';$('walkGate').className=w.deployable?'green':'red';$('walkMinRoi').textContent=pct(w.foldSummary?.minRoiPct);$('walkHoldRoi').textContent=pct(w.holdout?.roiPct)}catch(e){$('hit').textContent='Error';$('roi').textContent=e.message;$('deployGate').textContent='Error';$('deployGate').className='red'}}
$('wallet').onclick=async()=>{try{if(!window.ethereum)throw new Error('No EVM wallet found in this browser');const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)throw new Error('Wallet did not return an address');const x=await j('/api/wallet/connect',authed({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address})}));$('wallet').textContent=x.walletAddress?.slice(0,6)+'…'+x.walletAddress?.slice(-4)}catch(e){alert(e.message)}}
$('ask').onclick=async()=>{const prompt=$('prompt').value.trim();if(!prompt)return;$('chat').textContent='Thinking…';try{const x=await j('/api/gpt',authed({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt})}));$('chat').textContent=x.text||JSON.stringify(x,null,2)}catch(e){$('chat').textContent=e.message}}
$('runReplay').onclick=replay;$('refresh').onclick=opportunities;$('lane').onchange=opportunities;health();validation();opportunities();replay();setInterval(health,15000);setInterval(validation,30000);setInterval(opportunities,30000);
</script></body></html>`;
}
